#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /api

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login:
    path: /api/login
    methods: [POST]

api_refresh_token:
    path: /api/token_refresh
    methods: [POST]

logout:
    path: /api/logout
    controller: App\Controller\SecurityController::logout